services:
  mariadb:
    image: mariadb
    build:  ./requirements/mariadb/
    env_file: .env
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - inception
    container_name: mariadb
    secrets:
      - db_root_password
      - db_user_password

  wordpress:
    image: wordpress
    build:  ./requirements/wordpress/
    env_file: .env
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    container_name: wordpress
    depends_on:
      - mariadb
    secrets:
      - wp_user_password
      - wp_admin_password
      - db_user_password

  nginx:
    image: nginx
    build:  ./requirements/nginx/
    env_file: .env
    restart: always
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/html
    networks:
      - inception
    container_name: nginx
    depends_on:
      - wordpress
    secrets:
      - db_user_password

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress

secrets:
  db_root_password:
    file: ./secrets/db_root_password.txt
  db_user_password:
    file: ./secrets/db_user_password.txt
  wp_user_password:
    file: ./secrets/wp_user_password.txt
  wp_admin_password:
    file: ./secrets/wp_admin_password.txt

networks:
  inception:
    driver: bridge