services:
  mariadb:
    build:  ./requirements/mariadb/
    env_file: .env
    restart: always
    expose:
      - "3306"
    volumes:
      - mariadb:/var/lib/mysql
    container_name: mariadb

  wordpress:
    build:  ./requirements/wordpress/
    env_file: .env
    restart: always
    expose:
      - "9000"
    volumes:
      - wordpress:/var/www/html/wordpress
    container_name: wordpress
  

volumes:
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/mariadb
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${DATA_DIR}/wordpress
